spring:
  application:
    name: data-multidatasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/GoodsTransaction?serverTimezone=UTC
    username: root
    password: 123456
  second-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/GoodsTransaction?serverTimezone=UTC
    username: root
    password: 123456