dataSources:
  ds_master: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3307/GoodsTransaction?serverTimezone=UTC
    username: root
    password: 123456
  ds_slave: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3308/GoodsTransaction?serverTimezone=UTC
    username: root
    password: 123456

props:
  sql.show: false
