-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 02:50:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GoodsTransaction
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GoodsTransaction
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GoodsTransaction` DEFAULT CHARACTER SET utf8 ;
USE `GoodsTransaction` ;

-- -----------------------------------------------------
-- Table `GoodsTransaction`.`Goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoodsTransaction`.`Goods` ;

CREATE TABLE IF NOT EXISTS `GoodsTransaction`.`Goods` (
  `goods_id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `price` DECIMAL(6,2) NULL,
  `stock` INT NULL,
  `created_timestamp` TIMESTAMP(3) NULL,
  `updated_timestamp` TIMESTAMP(3) NULL,
  PRIMARY KEY (`goods_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoodsTransaction`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoodsTransaction`.`User` ;

CREATE TABLE IF NOT EXISTS `GoodsTransaction`.`User` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `created_timestamp` TIMESTAMP(3) NULL,
  `updated_timestamp` TIMESTAMP(3) NULL,
  `user_level` INT NULL,
  `lock` CHAR(1) NULL,
  `Deleted` CHAR(1) NULL,
  `Usercol` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoodsTransaction`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoodsTransaction`.`Order` ;

CREATE TABLE IF NOT EXISTS `GoodsTransaction`.`Order` (
  `order_id` INT NOT NULL,
  `User_user_id` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `photonumber` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `total_price` DECIMAL(6,2) NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_Order_User1_idx` (`User_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `GoodsTransaction`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoodsTransaction`.`order_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoodsTransaction`.`order_details` ;

CREATE TABLE IF NOT EXISTS `GoodsTransaction`.`order_details` (
  `Goods_goods_id` INT NOT NULL,
  `Order_order_id` INT NOT NULL,
  `goods_quntity` INT NOT NULL,
  `single_order_price` DECIMAL(6,2) NULL,
  PRIMARY KEY (`Goods_goods_id`, `Order_order_id`),
  INDEX `fk_order_details_order_idx` (`Order_order_id` ASC) VISIBLE,
  INDEX `fk_order_details_Goods1_idx` (`Goods_goods_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_details_order`
    FOREIGN KEY (`Order_order_id`)
    REFERENCES `GoodsTransaction`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_details_Goods1`
    FOREIGN KEY (`Goods_goods_id`)
    REFERENCES `GoodsTransaction`.`Goods` (`goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoodsTransaction`.`Goods_Edit_History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GoodsTransaction`.`Goods_Edit_History` ;

CREATE TABLE IF NOT EXISTS `GoodsTransaction`.`Goods_Edit_History` (
  `Goods_Edit_History_id` INT NOT NULL,
  `Goods_goods_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `edit_operation` VARCHAR(45) NULL,
  `Goods_Edit_Historycol` VARCHAR(45) NULL,
  `created_timestamp` TIMESTAMP(3) NULL,
  `stock` INT NULL,
  `price` VARCHAR(45) NULL,
  PRIMARY KEY (`Goods_Edit_History_id`),
  INDEX `fk_Goods_Edit_History_Goods1_idx` (`Goods_goods_id` ASC) VISIBLE,
  CONSTRAINT `fk_Goods_Edit_History_Goods1`
    FOREIGN KEY (`Goods_goods_id`)
    REFERENCES `GoodsTransaction`.`Goods` (`goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
